# Generated by Django 5.0 on 2024-01-06 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_apellido_persona_email_persona_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('no_calle', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personas.domicilio'),
            preserve_default=False,
        ),
    ]
