# Generated by Django 5.0 on 2024-01-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_rename_domicilio_persona_domicilioo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='domicilioo',
            new_name='domicilio',
        ),
    ]
